###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  pigeon-games:
    name: Browser Games
    desc: ✨ BrowserGames by PIGEONPOSSE
    type:
      - web
      - pwa
      - desktop-app
      - macos-app
      - linux-app
      - windows-app
    status: abandoned

###############################################################################
