###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  pigeon-games:
    name: "Browser Games"
    type:
      - "web"
      - "pwa"
      - "desktop-app"
      - "macos-app"
      - "linux-app"
      - "windows-app"
    status: "abandoned"

###############################################################################
